### ISSUE TITLE
More Architectures

### ISSUE THREAD

**Issue by TanzHasan** [ClangBuiltLinux/IWYUScripts#47]
Sh is an architecture that is broken by this
https://lore.kernel.org/llvm/20231205132452.418722bea8f6878dca88142a@linux-foundation.org/T/#t

More architectures need to be tested in order for this tool to better function.

**Comment by nickdesaulniers** [comment]
I think you should be able to fetch compilers for the GCC supported targets from https://mirrors.edge.kernel.org/pub/tools/crosstool/. From there, it will be more work to build each target since GCC requires more than just `ARCH=` for the command line invocation of `make` (`CROSS_COMPILE=<target triple prefix>-` is a necessary edition).

**Comment by nickdesaulniers** [comment]
It might be neat to add something like:

for $ARCH in supported targets:
  if $ARCH-linux-gnu-gcc is detected in the $PATH:
    run a build for $ARCH
